## Server Configuration
SERVER_NAME: "web-service"
SERVER_IP: "127.0.0.1"
SERVER_PORT: "8080"
SERVER_STORE_PATH: "./config/stores"
SERVER_UPLOAD_PATH: "./config/uploads"
SERVER_UPLOAD_LIMIT: 8
SERVER_LOG_LEVEL: "debug"

## Router Configuration
ROUTER_BASE_PATH: ""

## Cryptography Configuration
CRYPT_PRIVATE_KEY_FILE: "./config/keys/private.key"
CRYPT_PUBLIC_KEY_FILE: "./config/keys/public.key"

## Database Configuration

DB_DRIVER: "postgres"
DB_HOST: "127.0.0.1"
DB_PORT: "5432"
DB_USER: "postgres"
DB_PASSWORD: "password"
DB_NAME: "web_service"

## Local Cache Configuration
LOCAL_CACHE_LIB: "ristretto"
LOCAL_CACHE_MAX_COST: 1073741824 #maximum cost of cache (1GB = 2 ^ 30 bits)
LOCAL_CACHE_NUM_COUNTERS: 1e7 #number of keys to track frequency of items (10 milions)
LOCAL_CACHE_BUFFER_ITEMS: 64 #number of keys per get buffer
LOCAL_CACHE_METRICS: true #show statistics
